---
- name: Ensure iptables is installed.
  package: name=iptables state=installed

- include: rules.yml

- include: persist-debian.yml
  when: ansible_os_family == 'Debian'

- include: persist-redhat.yml
  when: ansible_os_family == 'RedHat'
